# version: "3.8"
services:
  book-service:
    build: .
    image: book-service:latest
    container_name: bookservice
    ports:
      - 3000:3000
    # networks:
      # - app-network
    environment:
      - JWT_SECRET=aqrabminto_db_user
    